In [ ]:
import pandas as pd
import numpy as np
from google.colab import files
files = files.upload()

Saving Churn_Modelling.csv to Churn_Modelling (1).csv

In [ ]:
df = pd.read_csv('Churn_Modelling.csv')

In [ ]:
df.head(2)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0

In [ ]:
df = pd.read_csv('Churn_Modelling.csv') # Reload the original DataFrame
df = df.drop(columns=['RowNumber','CustomerId','Surname'])

In [ ]:
df.head(2)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0

In [ ]:
df.shape

(10000, 11)

In [ ]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [ ]:
df = pd.read_csv('Churn_Modelling.csv') # Reload the original DataFrame
df = df.drop(columns=['RowNumber','CustomerId','Surname'])
df = pd.get_dummies(df,columns=['Geography','Gender'],drop_first=True,dtype=int)

In [ ]:
X = df.drop(columns=['Exited'])
y = df['Exited']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
df.head(2)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,1,0

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_trf = scaler.fit_transform(X_train)
X_test_trf = scaler.transform(X_test)

In [ ]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()
model.add(Dense(11,activation='sigmoid',input_dim=11))
model.add(Dense(11,activation='sigmoid'))
model.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 276 (1.08 KB)

 Trainable params: 276 (1.08 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
history = model.fit(X_train,y_train,batch_size=50,epochs=100,verbose=1,validation_split=0.2)

Epoch 1/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.6353 - loss: 0.6249 - val_accuracy: 0.7987 - val_loss: 0.5036
Epoch 2/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7940 - loss: 0.5065 - val_accuracy: 0.7987 - val_loss: 0.4937
Epoch 3/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.7937 - loss: 0.5012 - val_accuracy: 0.7987 - val_loss: 0.4928
Epoch 4/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.7902 - loss: 0.5064 - val_accuracy: 0.7987 - val_loss: 0.4926
Epoch 5/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7952 - loss: 0.5016 - val_accuracy: 0.7987 - val_loss: 0.4922
Epoch 6/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7958 - loss: 0.4993 - val_accuracy: 0.7987 - val_loss: 0.4919
Epoch 7/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7945 - loss: 0.5023 - val_accuracy: 0.7987 - val_loss: 0.4918
Epoch 8/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7859 - loss: 0.5127 - val_accuracy: 0.7987 - val_loss: 0.4917
Epoch 9/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7952 - loss: 0.5003 - val_accuracy: 0.7987 - val_loss: 0.4915
Epoch 10/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7966 - loss: 0.4971 - val_accuracy: 0.7987 - val_loss: 0.4924
Epoch 11/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7891 - loss: 0.5089 - val_accuracy: 0.7987 - val_loss: 0.4918
Epoch 12/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7882 - loss: 0.5081 - val_accuracy: 0.7987 - val_loss: 0.4917
Epoch 13/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8019 - loss: 0.4931 - val_accuracy: 0.7987 - val_loss: 0.4921
Epoch 14/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7954 - loss: 0.5006 - val_accuracy: 0.7987 - val_loss: 0.4917
Epoch 15/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7963 - loss: 0.4968 - val_accuracy: 0.7987 - val_loss: 0.4918
Epoch 16/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7966 - loss: 0.4990 - val_accuracy: 0.7987 - val_loss: 0.4921
Epoch 17/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8020 - loss: 0.4899 - val_accuracy: 0.7987 - val_loss: 0.4920
Epoch 18/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7954 - loss: 0.5005 - val_accuracy: 0.7987 - val_loss: 0.4917
Epoch 19/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7944 - loss: 0.5007 - val_accuracy: 0.7987 - val_loss: 0.4917
Epoch 20/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7830 - loss: 0.5172 - val_accuracy: 0.7987 - val_loss: 0.4916
Epoch 21/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7940 - loss: 0.5018 - val_accuracy: 0.7987 - val_loss: 0.4921
Epoch 22/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7898 - loss: 0.5073 - val_accuracy: 0.7987 - val_loss: 0.4917
Epoch 23/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7961 - loss: 0.4989 - val_accuracy: 0.7987 - val_loss: 0.4920
Epoch 24/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7877 - loss: 0.5107 - val_accuracy: 0.7987 - val_loss: 0.4917
Epoch 25/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7991 - loss: 0.4965 - val_accuracy: 0.7987 - val_loss: 0.4918
Epoch 26/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7926 - loss: 0.5023 - val_accuracy: 0.7987 - val_loss: 0.4917
Epoch 27/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7907 - loss: 0.5036 - val_accuracy: 0.7987 - val_loss: 0.4917
Epoch 28/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8002 - loss: 0.4922 - val_accuracy: 0.7987 - val_loss: 0.4920
Epoch 29/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7951 - loss: 0.5003 - val_accuracy: 0.7987 - val_loss: 0.4923
Epoch 30/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7953 - loss: 0.4996 - val_accuracy: 0.7987 - val_loss: 0.4917
Epoch 31/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7912 - loss: 0.5033 - val_accuracy: 0.7987 - val_loss: 0.4918
Epoch 32/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7957 - loss: 0.4985 - val_accuracy: 0.7987 - val_loss: 0.4916
Epoch 33/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7988 - loss: 0.4947 - val_accuracy: 0.7987 - val_loss: 0.4918
Epoch 34/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7787 - loss: 0.5212 - val_accuracy: 0.7987 - val_loss: 0.4919
Epoch 35/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7986 - loss: 0.4943 - val_accuracy: 0.7987 - val_loss: 0.4916
Epoch 36/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8051 - loss: 0.4866 - val_accuracy: 0.7987 - val_loss: 0.4922
Epoch 37/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7907 - loss: 0.5096 - val_accuracy: 0.7987 - val_loss: 0.4918
Epoch 38/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7847 - loss: 0.5153 - val_accuracy: 0.7987 - val_loss: 0.4916
Epoch 39/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8046 - loss: 0.4861 - val_accuracy: 0.7987 - val_loss: 0.4922
Epoch 40/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7889 - loss: 0.5056 - val_accuracy: 0.7987 - val_loss: 0.4917
Epoch 41/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7827 - loss: 0.5167 - val_accuracy: 0.7987 - val_loss: 0.4917
Epoch 42/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7959 - loss: 0.4996 - val_accuracy: 0.7987 - val_loss: 0.4917
Epoch 43/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7884 - loss: 0.5070 - val_accuracy: 0.7987 - val_loss: 0.4917
Epoch 44/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7906 - loss: 0.5063 - val_accuracy: 0.7987 - val_loss: 0.4917
Epoch 45/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7907 - loss: 0.5044 - val_accuracy: 0.7987 - val_loss: 0.4917
Epoch 46/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8021 - loss: 0.4893 - val_accuracy: 0.7987 - val_loss: 0.4921
Epoch 47/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7884 - loss: 0.5090 - val_accuracy: 0.7987 - val_loss: 0.4918
Epoch 48/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7910 - loss: 0.5051 - val_accuracy: 0.7987 - val_loss: 0.4918
Epoch 49/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7988 - loss: 0.4942 - val_accuracy: 0.7987 - val_loss: 0.4925
Epoch 50/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7869 - loss: 0.5111 - val_accuracy: 0.7987 - val_loss: 0.4918
Epoch 51/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7966 - loss: 0.4964 - val_accuracy: 0.7987 - val_loss: 0.4918
Epoch 52/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7987 - loss: 0.4962 - val_accuracy: 0.7987 - val_loss: 0.4922
Epoch 53/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7840 - loss: 0.5125 - val_accuracy: 0.7987 - val_loss: 0.4917
Epoch 54/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7970 - loss: 0.4987 - val_accuracy: 0.7987 - val_loss: 0.4920
Epoch 55/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7870 - loss: 0.5100 - val_accuracy: 0.7987 - val_loss: 0.4920
Epoch 56/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7947 - loss: 0.5021 - val_accuracy: 0.7987 - val_loss: 0.4918
Epoch 57/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7921 - loss: 0.5037 - val_accuracy: 0.7987 - val_loss: 0.4918
Epoch 58/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8039 - loss: 0.4878 - val_accuracy: 0.7987 - val_loss: 0.4921
Epoch 59/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7949 - loss: 0.4986 - val_accuracy: 0.7987 - val_loss: 0.4918
Epoch 60/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7962 - loss: 0.4961 - val_accuracy: 0.7987 - val_loss: 0.4918
Epoch 61/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7944 - loss: 0.5026 - val_accuracy: 0.7987 - val_loss: 0.4920
Epoch 62/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7938 - loss: 0.5006 - val_accuracy: 0.7987 - val_loss: 0.4918
Epoch 63/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7968 - loss: 0.4954 - val_accuracy: 0.7987 - val_loss: 0.4922
Epoch 64/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7958 - loss: 0.4967 - val_accuracy: 0.7987 - val_loss: 0.4920
Epoch 65/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7840 - loss: 0.5151 - val_accuracy: 0.7987 - val_loss: 0.4918
Epoch 66/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7885 - loss: 0.5079 - val_accuracy: 0.7987 - val_loss: 0.4919
Epoch 67/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7890 - loss: 0.5093 - val_accuracy: 0.7987 - val_loss: 0.4919
Epoch 68/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7878 - loss: 0.5103 - val_accuracy: 0.7987 - val_loss: 0.4919
Epoch 69/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7956 - loss: 0.4993 - val_accuracy: 0.7987 - val_loss: 0.4921
Epoch 70/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7954 - loss: 0.5003 - val_accuracy: 0.7987 - val_loss: 0.4923
Epoch 71/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8057 - loss: 0.4870 - val_accuracy: 0.7987 - val_loss: 0.4927
Epoch 72/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8063 - loss: 0.4861 - val_accuracy: 0.7987 - val_loss: 0.4924
Epoch 73/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7926 - loss: 0.5016 - val_accuracy: 0.7987 - val_loss: 0.4919
Epoch 74/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7917 - loss: 0.5041 - val_accuracy: 0.7987 - val_loss: 0.4921
Epoch 75/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7982 - loss: 0.4972 - val_accuracy: 0.7987 - val_loss: 0.4921
Epoch 76/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7912 - loss: 0.5038 - val_accuracy: 0.7987 - val_loss: 0.4918
Epoch 77/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8016 - loss: 0.4868 - val_accuracy: 0.7987 - val_loss: 0.4922
Epoch 78/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7992 - loss: 0.4926 - val_accuracy: 0.7987 - val_loss: 0.4927
Epoch 79/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8002 - loss: 0.4947 - val_accuracy: 0.7987 - val_loss: 0.4920
Epoch 80/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7930 - loss: 0.5018 - val_accuracy: 0.7987 - val_loss: 0.4920
Epoch 81/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8008 - loss: 0.4933 - val_accuracy: 0.7987 - val_loss: 0.4923
Epoch 82/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7905 - loss: 0.5066 - val_accuracy: 0.7987 - val_loss: 0.4918
Epoch 83/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7939 - loss: 0.5024 - val_accuracy: 0.7987 - val_loss: 0.4918
Epoch 84/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7977 - loss: 0.4958 - val_accuracy: 0.7987 - val_loss: 0.4919
Epoch 85/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7941 - loss: 0.5029 - val_accuracy: 0.7987 - val_loss: 0.4919
Epoch 86/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7829 - loss: 0.5176 - val_accuracy: 0.7987 - val_loss: 0.4921
Epoch 87/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7944 - loss: 0.5006 - val_accuracy: 0.7987 - val_loss: 0.4920
Epoch 88/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7967 - loss: 0.4969 - val_accuracy: 0.7987 - val_loss: 0.4918
Epoch 89/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8012 - loss: 0.4928 - val_accuracy: 0.7987 - val_loss: 0.4924
Epoch 90/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7927 - loss: 0.5041 - val_accuracy: 0.7987 - val_loss: 0.4918
Epoch 91/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7898 - loss: 0.5079 - val_accuracy: 0.7987 - val_loss: 0.4918
Epoch 92/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7929 - loss: 0.5011 - val_accuracy: 0.7987 - val_loss: 0.4918
Epoch 93/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7901 - loss: 0.5059 - val_accuracy: 0.7987 - val_loss: 0.4919
Epoch 94/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7924 - loss: 0.5016 - val_accuracy: 0.7987 - val_loss: 0.4919
Epoch 95/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7965 - loss: 0.4975 - val_accuracy: 0.7987 - val_loss: 0.4918
Epoch 96/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8035 - loss: 0.4897 - val_accuracy: 0.7987 - val_loss: 0.4921
Epoch 97/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7942 - loss: 0.5015 - val_accuracy: 0.7987 - val_loss: 0.4918
Epoch 98/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7929 - loss: 0.5020 - val_accuracy: 0.7987 - val_loss: 0.4917
Epoch 99/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7812 - loss: 0.5156 - val_accuracy: 0.7987 - val_loss: 0.4917
Epoch 100/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7958 - loss: 0.5027 - val_accuracy: 0.7987 - val_loss: 0.4919